from datetime import datetime

from .latex_command import cmd_add, cmd_del, impl_cmd_add, impl_cmd_del


def generate_info_header(fn_old: str, fn_new: str) -> str:
    now = datetime.now().astimezone()
    header = (
        "%DIF PYLATEXDIFF DIFFERENCE FILE\n"
        f"%DIF [OLD] {fn_old} -> [NEW] {fn_new}\n"
        f"%DIF GENERATED BY pylatexdiff AT {now.isoformat()}\n"
        "\n\n"
    )
    return header


def generate_style_header(
    style_add: str,
    style_del: str
) -> str:

    header = (
r"""% BEGIN PyLaTeXDiff Preamble
\RequirePackage{soul}
\RequirePackage{empheq}
\RequirePackage{xcolor}

\definecolor{diffgreen}{HTML}{28a745} % Addition
\definecolor{diffred}{HTML}{d73a49}   % Deletion

"""
        r"\providecommand{" + cmd_add + "}[1]{" + impl_cmd_add(style_add) + "}\n"
        r"\providecommand{" + cmd_del + "}[1]{" + impl_cmd_del(style_del) + "}\n"
        r"% END PyLaTeXDiff Preamble"
        "\n\n\n"
    )

    return header


if __name__ == "__main__":
    pass